version: "{build}"

environment:
  matrix:
    # For regular jobs, such as push, pr and etc.
  #  - job_name: Linux
  #    appveyor_build_worker_image: ubuntu2004
    - job_name: MacOS
      appveyor_build_worker_image: macos-bigsur
  #  - job_name: Windows
  #    appveyor_build_worker_image: Visual Studio 2019
  #  - job_name: Deploy
  #    appveyor_build_worker_image: ubuntu2004

for:
  - # Linux and MacOS
    skip_tags: true
    matrix:
      only:
        #- job_name: Linux
        - job_name: MacOS

    install:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.42.0
      - go mod vendor

    before_build:
      - golangci-lint cache clean
      - make check

#  - # Windows
#    skip_tags: true
#    matrix:
#      only:
#        - job_name: Windows
#
#    environment:
#      matrix:
#        - GOARCH: amd64
#
#    install:
#      - choco install make
#      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.42.0
#      - go mod vendor
#      - set PATH=C:\Users\appveyor\go\bin;C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%
#
#    before_build:
#      - set GO111MODULE=on
#      - golangci-lint cache clean
#      - make check-windows
#
#    build_script:
#      - make build-windows

  - # Deploy
    build: off
    matrix:
      only:
        - job_name: Deploy
    branches:
      only:
        - develop
        - master
    deploy:
      provider: Script
      on:
        branch:
          - master
          - develop
    before_deploy:
      - bash ./docker/scripts/docker-push.sh -t "$APPVEYOR_REPO_BRANCH" -p
    deploy_script:
      - echo "Complete!"
