# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com

release:
  github:
    owner: skycoin
    name: dmsg

  prerelease: true

before:
  hooks:
    - go mod tidy

env:
  - CGO_ENABLED=0

common_flags: >
  -s -w -X github.com/skycoin/skywire-utilities/pkg/buildinfo.version=v{{.Version}}
  -X github.com/skycoin/skywire-utilities/pkg/buildinfo.commit={{.ShortCommit}}
  -X github.com/skycoin/skywire-utilities/pkg/buildinfo.date={{.Date}}

  - id: dmsgcurl
    binary: dmsgcurl
    goos:
      - darwin
    goarch:
      - arm64
      - amd64
    env:
      - CGO_ENABLED=0
    main: ./cmd/dmsgcurl/
    ldflags: -s -w -X github.com/skycoin/skywire-utilities/pkg/buildinfo.version=v{{.Version}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.commit={{.ShortCommit}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.date={{.Date}}

targets:
  - name: dmsg-discovery
    id: discovery
    arch: arm64

  - name: dmsg-server
    id: server
    arch: arm64

  - name: dmsgget
    id: get
    arch: arm64

  - name: dmsgpost
    id: post
    arch: arm64

  - name: dmsghttp
    id: http
    arch: arm64

  - name: dmsgpty-ui
    id: ui
    arch: arm64

  - name: dmsgpty-cli
    id: cli
    arch: arm64

  - name: dmsgpty-host
    id: host
    arch: arm64

builds: &builds
  {{ range .Targets }}
  - id: {{ .id }}-{{ .arch }}
    binary: {{ .name }}
    goarch:
      - {{ .arch }}
    <<: *common_build
  {{ end }}

  - id: dmsgweb
    binary: dmsgweb
    goos:
      - darwin
    goarch:
      - arm64
      - amd64
    env:
      - CGO_ENABLED=0
    main: ./cmd/dmsgweb/
    ldflags: -s -w -X github.com/skycoin/skywire-utilities/pkg/buildinfo.version=v{{.Version}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.commit={{.ShortCommit}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.date={{.Date}}

archives:
  - id: archive
    format: tar.gz
    wrap_in_directory: false
    name_template: 'dmsg-v{{ .Version }}-{{ .Os }}-{{ .Arch }}'
    builds:
      - dmsg-discovery
      - dmsg-server
      - dmsgpty-ui
      - dmsgpty-host
      - dmsgcurl
      - dmsgpty-cli
      - dmsgweb
    allow_different_binary_count: true

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
