# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com

release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL or empty if its private hosted.
  # Note: it can only be one: either github or gitlab or gitea
  github:
    owner: skycoin
    name: dmsg

  prerelease: true

before:
  hooks:
    - go mod tidy

builds:
  - id: dmsg-discovery
    binary: dmsg-discovery
    goos:
      - darwin
    goarch:
      - arm64
      - amd64
    env:
      - CGO_ENABLED=1
    main: ./cmd/dmsg-discovery/
    ldflags: -s -w -X github.com/skycoin/skywire-utilities/pkg/buildinfo.version=v{{.Version}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.commit={{.ShortCommit}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.date={{.Date}}

  - id: dmsg-server
    binary: dmsg-server
    goos:
      - darwin
    goarch:
      - arm64
      - amd64
    env:
      - CGO_ENABLED=0
    main: ./cmd/dmsg-server/
    ldflags: -s -w -X github.com/skycoin/skywire-utilities/pkg/buildinfo.version=v{{.Version}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.commit={{.ShortCommit}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.date={{.Date}}

  - id: dmsgcurl
    binary: dmsgcurl
    goos:
      - darwin
    goarch:
      - arm64
      - amd64
    env:
      - CGO_ENABLED=0
    main: ./cmd/dmsgcurl/
    ldflags: -s -w -X github.com/skycoin/skywire-utilities/pkg/buildinfo.version=v{{.Version}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.commit={{.ShortCommit}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.date={{.Date}}

  - id: dmsgpty-ui
    binary: dmsgpty-ui
    goos:
      - darwin
    goarch:
      - arm64
      - amd64
    env:
      - CGO_ENABLED=0
    main: ./cmd/dmsgpty-ui/
    ldflags: -s -w -X github.com/skycoin/skywire-utilities/pkg/buildinfo.version=v{{.Version}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.commit={{.ShortCommit}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.date={{.Date}}

  - id: dmsgpty-host
    binary: dmsgpty-host
    goos:
      - darwin
    goarch:
      - arm64
      - amd64
    env:
      - CGO_ENABLED=0
    main: ./cmd/dmsgpty-host/
    ldflags: -s -w -X github.com/skycoin/skywire-utilities/pkg/buildinfo.version=v{{.Version}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.commit={{.ShortCommit}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.date={{.Date}}

  - id: dmsgpty-cli
    binary: dmsgpty-cli
    goos:
      - darwin
    goarch:
      - arm64
      - amd64
    env:
      - CGO_ENABLED=0
    main: ./cmd/dmsgpty-cli/
    ldflags: -s -w -X github.com/skycoin/skywire-utilities/pkg/buildinfo.version=v{{.Version}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.commit={{.ShortCommit}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.date={{.Date}}

archives:
  - id: archive
    format: tar.gz
    wrap_in_directory: false
    name_template: 'dmsg-v{{ .Version }}-{{ .Os }}-{{ .Arch }}'
    builds:
      - dmsg-discovery
      - dmsg-server
      - dmsgpty-ui
      - dmsgpty-host
      - dmsgcurl
      - dmsgpty-cli
    allow_different_binary_count: true

checksum:
  name_template: 'checksums.txt'  
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
