# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com

release:
  github:
    owner: skycoin
    name: dmsg

  prerelease: false

before:
  hooks:
    - go mod tidy

env:
  - CGO_ENABLED=0

  - id: dmsgcurl
    binary: dmsgcurl
    goos:
      - windows
    goarch:
      - amd64
      - 386
    env:
      - CGO_ENABLED=0
    main: ./cmd/dmsgcurl/
    ldflags: -s -w -X github.com/skycoin/skywire-utilities/pkg/buildinfo.version=v{{.Version}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.commit={{.ShortCommit}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.date={{.Date}}

  - id: dmsgpty-ui
    binary: dmsgpty-ui
    goos:
      - windows
    goarch:
      - amd64
      - 386
    env:
      - CGO_ENABLED=0
    main: ./cmd/dmsgpty-ui/
    ldflags: -s -w -X github.com/skycoin/skywire-utilities/pkg/buildinfo.version=v{{.Version}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.commit={{.ShortCommit}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.date={{.Date}}

common_build: &common_build
  goos:
    - windows
  main: ./cmd/{{ .name }}/
  ldflags: *common_flags

targets:
  - name: dmsg-discovery
    id: discovery
    arch: amd64

  - name: dmsg-server
    id: server
    arch: amd64

  - name: dmsgget
    id: get
    arch: amd64

  - name: dmsgpost
    id: post
    arch: amd64

  - name: dmsghttp
    id: http
    arch: amd64

  - name: dmsgpty-ui
    id: ui
    arch: amd64

  - name: dmsgpty-cli
    id: cli
    arch: amd64

  - name: dmsgpty-host
    id: host
    arch: amd64

builds: &builds
  {{ range .Targets }}
  - id: {{ .id }}-{{ .arch }}
    binary: {{ .name }}
    goarch:
      - {{ .arch }}
    <<: *common_build
  {{ end }}

  - id: dmsgweb
    binary: dmsgweb
    goos:
      - windows
    goarch:
      - amd64
      - 386
    env:
      - CGO_ENABLED=0
    main: ./cmd/dmsgweb/
    ldflags: -s -w -X github.com/skycoin/skywire-utilities/pkg/buildinfo.version=v{{.Version}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.commit={{.ShortCommit}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.date={{.Date}}

archives:
  - id: archive
    format: zip
    wrap_in_directory: false
    name_template: 'dmsg-v{{ .Version }}-{{ .Os }}-{{ .Arch }}'
    builds:
      - dmsg-discovery
      - dmsg-server
      - dmsgcurl
      - dmsgpty-cli
      - dmsgpty-ui
      - dmsgpty-host
    allow_different_binary_count: true

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
